// data/bible.ts

import { BibleBook, BibleVerse } from "@/types/bible";

export const bibleBooks: BibleBook[] = [
  { id: 1, name: "Genesis", slug: "genesis", chapters: 50, testament: "Old" },
  { id: 2, name: "Exodus", slug: "exodus", chapters: 40, testament: "Old" },
  { id: 3, name: "Leviticus", slug: "leviticus", chapters: 27, testament: "Old" },
  { id: 4, name: "Numbers", slug: "numbers", chapters: 36, testament: "Old" },
  { id: 5, name: "Deuteronomy", slug: "deuteronomy", chapters: 34, testament: "Old" },
  { id: 6, name: "Joshua", slug: "joshua", chapters: 24, testament: "Old" },
  { id: 7, name: "Judges", slug: "judges", chapters: 21, testament: "Old" },
  { id: 8, name: "Ruth", slug: "ruth", chapters: 4, testament: "Old" },
  { id: 9, name: "1 Samuel", slug: "1-samuel", chapters: 31, testament: "Old" },
  { id: 10, name: "2 Samuel", slug: "2-samuel", chapters: 24, testament: "Old" },
  { id: 11, name: "1 Kings", slug: "1-kings", chapters: 22, testament: "Old" },
  { id: 12, name: "2 Kings", slug: "2-kings", chapters: 25, testament: "Old" },
  { id: 13, name: "1 Chronicles", slug: "1-chronicles", chapters: 29, testament: "Old" },
  { id: 14, name: "2 Chronicles", slug: "2-chronicles", chapters: 36, testament: "Old" },
  { id: 15, name: "Ezra", slug: "ezra", chapters: 10, testament: "Old" },
  { id: 16, name: "Nehemiah", slug: "nehemiah", chapters: 13, testament: "Old" },
  { id: 17, name: "Esther", slug: "esther", chapters: 10, testament: "Old" },
  { id: 18, name: "Job", slug: "job", chapters: 42, testament: "Old" },
  { id: 19, name: "Psalms", slug: "psalms", chapters: 150, testament: "Old" },
  { id: 20, name: "Proverbs", slug: "proverbs", chapters: 31, testament: "Old" },
  { id: 21, name: "Ecclesiastes", slug: "ecclesiastes", chapters: 12, testament: "Old" },
  { id: 22, name: "Song of Solomon", slug: "song-of-solomon", chapters: 8, testament: "Old" },
  { id: 23, name: "Isaiah", slug: "isaiah", chapters: 66, testament: "Old" },
  { id: 24, name: "Jeremiah", slug: "jeremiah", chapters: 52, testament: "Old" },
  { id: 25, name: "Lamentations", slug: "lamentations", chapters: 5, testament: "Old" },
  { id: 26, name: "Ezekiel", slug: "ezekiel", chapters: 48, testament: "Old" },
  { id: 27, name: "Daniel", slug: "daniel", chapters: 12, testament: "Old" },
  { id: 28, name: "Hosea", slug: "hosea", chapters: 14, testament: "Old" },
  { id: 29, name: "Joel", slug: "joel", chapters: 3, testament: "Old" },
  { id: 30, name: "Amos", slug: "amos", chapters: 9, testament: "Old" },
  { id: 31, name: "Obadiah", slug: "obadiah", chapters: 1, testament: "Old" },
  { id: 32, name: "Jonah", slug: "jonah", chapters: 4, testament: "Old" },
  { id: 33, name: "Micah", slug: "micah", chapters: 7, testament: "Old" },
  { id: 34, name: "Nahum", slug: "nahum", chapters: 3, testament: "Old" },
  { id: 35, name: "Habakkuk", slug: "habakkuk", chapters: 3, testament: "Old" },
  { id: 36, name: "Zephaniah", slug: "zephaniah", chapters: 3, testament: "Old" },
  { id: 37, name: "Haggai", slug: "haggai", chapters: 2, testament: "Old" },
  { id: 38, name: "Zechariah", slug: "zechariah", chapters: 14, testament: "Old" },
  { id: 39, name: "Malachi", slug: "malachi", chapters: 4, testament: "Old" },
  { id: 40, name: "Matthew", slug: "matthew", chapters: 28, testament: "New" },
  { id: 41, name: "Mark", slug: "mark", chapters: 16, testament: "New" },
  { id: 42, name: "Luke", slug: "luke", chapters: 24, testament: "New" },
  { id: 43, name: "John", slug: "john", chapters: 21, testament: "New" },
  { id: 44, name: "Acts", slug: "acts", chapters: 28, testament: "New" },
  { id: 45, name: "Romans", slug: "romans", chapters: 16, testament: "New" },
  { id: 46, name: "1 Corinthians", slug: "1-corinthians", chapters: 16, testament: "New" },
  { id: 47, name: "2 Corinthians", slug: "2-corinthians", chapters: 13, testament: "New" },
  { id: 48, name: "Galatians", slug: "galatians", chapters: 6, testament: "New" },
  { id: 49, name: "Ephesians", slug: "ephesians", chapters: 6, testament: "New" },
  { id: 50, name: "Philippians", slug: "philippians", chapters: 4, testament: "New" },
  { id: 51, name: "Colossians", slug: "colossians", chapters: 4, testament: "New" },
  { id: 52, name: "1 Thessalonians", slug: "1-thessalonians", chapters: 5, testament: "New" },
  { id: 53, name: "2 Thessalonians", slug: "2-thessalonians", chapters: 3, testament: "New" },
  { id: 54, name: "1 Timothy", slug: "1-timothy", chapters: 6, testament: "New" },
  { id: 55, name: "2 Timothy", slug: "2-timothy", chapters: 4, testament: "New" },
  { id: 56, name: "Titus", slug: "titus", chapters: 3, testament: "New" },
  { id: 57, name: "Philemon", slug: "philemon", chapters: 1, testament: "New" },
  { id: 58, name: "Hebrews", slug: "hebrews", chapters: 13, testament: "New" },
  { id: 59, name: "James", slug: "james", chapters: 5, testament: "New" },
  { id: 60, name: "1 Peter", slug: "1-peter", chapters: 5, testament: "New" },
  { id: 61, name: "2 Peter", slug: "2-peter", chapters: 3, testament: "New" },
  { id: 62, name: "1 John", slug: "1-john", chapters: 5, testament: "New" },
  { id: 63, name: "2 John", slug: "2-john", chapters: 1, testament: "New" },
  { id: 64, name: "3 John", slug: "3-john", chapters: 1, testament: "New" },
  { id: 65, name: "Jude", slug: "jude", chapters: 1, testament: "New" },
  { id: 66, name: "Revelation", slug: "revelation", chapters: 22, testament: "New" },
];

// Sample verses - in a real app, you'd have all verses
export const bibleVerses: BibleVerse[] = [
  // Genesis 1
  { bookId: 1, bookName: "Genesis", chapter: 1, verse: 1, text: "In the beginning God created the heavens and the earth." },
  { bookId: 1, bookName: "Genesis", chapter: 1, verse: 2, text: "Now the earth was formless and empty, darkness was over the surface of the deep, and the Spirit of God was hovering over the waters." },
  { bookId: 1, bookName: "Genesis", chapter: 1, verse: 3, text: "And God said, \"Let there be light,\" and there was light." },
  
  // John 3:16
  { bookId: 43, bookName: "John", chapter: 3, verse: 16, text: "For God so loved the world that he gave his one and only Son, that whoever believes in him shall not perish but have eternal life." },
  
  // Psalm 23
  { bookId: 19, bookName: "Psalms", chapter: 23, verse: 1, text: "The LORD is my shepherd, I lack nothing." },
  { bookId: 19, bookName: "Psalms", chapter: 23, verse: 2, text: "He makes me lie down in green pastures, he leads me beside quiet waters," },
  { bookId: 19, bookName: "Psalms", chapter: 23, verse: 3, text: "he refreshes my soul. He guides me along the right paths for his name's sake." },
];